version: "3.9"

services:
  web:
    build:
      context: .
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

volumes:
  db_data:
