# Generated by Django 4.1.7 on 2023-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='csvdocument',
            name='filename',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
